#include <gtest/gtest.h> //clang-unit-cpp: Required for running tests
#include "test.cpp" //clang-unit-cpp: Includes the tested file

TEST(AutogeneratedStubSuite, NiceStructTestStub) {
	Outer::Inner::NiceStruct::NiceStruct objectNiceStruct();
	/* Fill Me! */
}

TEST(AutogeneratedStubSuite, NiceStructTestStub) {
	Outer::Inner::NiceStruct::NiceStruct objectNiceStruct(std::string &);
	/* Fill Me! */
}

TEST(AutogeneratedStubSuite, get_lengthTestStub) {
	Outer::Inner::NiceStruct object;
	EXPECT_EQ(object.get_length(), /* Fill Me! */);
}

TEST(AutogeneratedStubSuite, methodTestStub) {
	StandaloneStruct object;
	object.method();
	/* Fill Me! */
}

TEST(AutogeneratedStubSuite, return_structTestStub) {
	StandaloneStruct object;
	EXPECT_EQ(object.return_struct(Outer::Inner::NiceStruct &), /* Fill Me! */);
}

#include <gtest/gtest.h> //clang-unit-cpp: Required for running tests
#include "test.cpp" //clang-unit-cpp: Includes the tested file

TEST(AutogeneratedStubSuite, NiceStructTestStub) {
	Outer::Inner::NiceStruct::NiceStruct objectNiceStruct();
	/* Fill Me! */
}

TEST(AutogeneratedStubSuite, NiceStructTestStub) {
	Outer::Inner::NiceStruct::NiceStruct objectNiceStruct(std::string &);
	/* Fill Me! */
}

TEST(AutogeneratedStubSuite, get_lengthTestStub) {
	Outer::Inner::NiceStruct object;
	EXPECT_EQ(object.get_length(), /* Fill Me! */);
}

TEST(AutogeneratedStubSuite, methodTestStub) {
	StandaloneStruct object;
	object.method();
	/* Fill Me! */
}

TEST(AutogeneratedStubSuite, return_structTestStub) {
	StandaloneStruct object;
	EXPECT_EQ(object.return_struct(Outer::Inner::NiceStruct &), /* Fill Me! */);
}

#include <gtest/gtest.h> //clang-unit-cpp: Required for running tests
#include "test.cpp" //clang-unit-cpp: Includes the tested file

TEST(AutogeneratedStubSuite, NiceStructTestStub) {
	Outer::Inner::NiceStruct::NiceStruct objectNiceStruct();
	/* Fill Me! */
}

TEST(AutogeneratedStubSuite, NiceStructTestStub) {
	Outer::Inner::NiceStruct::NiceStruct objectNiceStruct(std::string &);
	/* Fill Me! */
}

TEST(AutogeneratedStubSuite, get_lengthTestStub) {
	Outer::Inner::NiceStruct object;
	EXPECT_EQ(object.get_length(), /* Fill Me! */);
}

TEST(AutogeneratedStubSuite, methodTestStub) {
	StandaloneStruct object;
	object.method();
	/* Fill Me! */
}

TEST(AutogeneratedStubSuite, return_structTestStub) {
	StandaloneStruct object;
	EXPECT_EQ(object.return_struct(Outer::Inner::NiceStruct &), /* Fill Me! */);
}

#include <gtest/gtest.h> //clang-unit-cpp: Required for running tests
#include "test.cpp" //clang-unit-cpp: Includes the tested file

TEST(AutogeneratedStubSuite, NiceStructTestStub) {
	Outer::Inner::NiceStruct::NiceStruct objectNiceStruct();
	/* Fill Me! */
}

TEST(AutogeneratedStubSuite, NiceStructTestStub) {
	Outer::Inner::NiceStruct::NiceStruct objectNiceStruct(std::string &);
	/* Fill Me! */
}

TEST(AutogeneratedStubSuite, get_lengthTestStub) {
	Outer::Inner::NiceStruct object;
	EXPECT_EQ(object.get_length(), /* Fill Me! */);
}

TEST(AutogeneratedStubSuite, methodTestStub) {
	StandaloneStruct object;
	object.method(int, long long, long, short, unsigned int, float, double, float, _Bool);
	/* Fill Me! */
}

TEST(AutogeneratedStubSuite, return_structTestStub) {
	StandaloneStruct object;
	EXPECT_EQ(object.return_struct(Outer::Inner::NiceStruct &), /* Fill Me! */);
}

