#pragma once
#include <string>
#include <fstream>
#include <memory>
#include <vector>
#include <map>

class HandlesOutputFiles
{
private:
protected:
    // stanisz: Returns a string representing a path to the file containing
    //          generated tests based on the path of the file under testing.
    //          You can specify the exact location of the test files
    //          that will be generated by overriding this funciton which does
    //          the input->output path mapping.
    //          This will be used by the private methods of this interface
    //          as a basis to open and write contents to the test files.
    virtual std::string to_output_source_path(std::string &input_source_path) const;

public:
    virtual ~HandlesOutputFiles() = default;
};